{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "0a910776_25e35975",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 7,
      "author": {
        "id": 6731
      },
      "writtenOn": "2024-02-13T09:35:50Z",
      "side": 1,
      "message": "Fix warning message when service creation fails",
      "revId": "2da6eca5db7a5ed0fd9bc357961e6fee4753a937",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4ecf9543_1f9280a2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 8358
      },
      "writtenOn": "2024-02-12T12:32:24Z",
      "side": 1,
      "message": "recheck",
      "revId": "2da6eca5db7a5ed0fd9bc357961e6fee4753a937",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "3a36f4b7_be201ff1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 8358
      },
      "writtenOn": "2024-02-12T15:26:47Z",
      "side": 1,
      "message": "I don\u0027t know what\u0027s going on with Python tests. They seem to fail at different random places every time.",
      "revId": "2da6eca5db7a5ed0fd9bc357961e6fee4753a937",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "46965a4a_8dd92873",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2024-02-13T09:36:32Z",
      "side": 1,
      "message": "very likely a LFN infra issue, let\u0027s do a recheck",
      "parentUuid": "3a36f4b7_be201ff1",
      "revId": "2da6eca5db7a5ed0fd9bc357961e6fee4753a937",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ec0798dc_24947f78",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2024-02-13T09:36:37Z",
      "side": 1,
      "message": "recheck",
      "revId": "2da6eca5db7a5ed0fd9bc357961e6fee4753a937",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}